Fixes for Swedish translation
ReactiveDrop/reactivedrop_translations pull request #1457
Opened 2024-03-18 08:34 UTC by icepic

2024-03-23 16:52 UTC, Crazymanbos requested changes

2024-03-23 16:52 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"rd_hoiaf_bounty_mission_bonus_claimed"		"Genom att klara av detta uppdrag, har %s1 samlat in en belöning på %s2 poäng! %s1 har samlat in %s3 poäng från uppdrag denna säsong.\n"
This one is incorrect, because the har (has) cant be before the bounty amount.

2024-03-23 16:52 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_weaponl_medical_satchel"		"PVs Medicinska väska med rem"
-

2024-03-23 16:52 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_take_ammo_flamer"		"Ta eldkastar-ammo"
The flamethrower is named "lågantändning" in this game, thats why it says låg-ammo.

2024-03-23 16:52 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_ammo_flamer"		"Eldkastar-ammo"
This one too

2024-03-23 16:52 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_ammo_flamer_full"		"Fulla Eldkastarmagasin"
Again

2024-03-26 19:19 UTC, BenLubar requested changes
please address the comments @Crazymanbos left so I can merge this

2024-03-27 11:31 UTC, icepic reviewed
Yes, those are an improvement.

2024-03-27 18:07 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"rd_hoiaf_bounty_mission_bonus_claimed"		"Genom att klara av detta uppdrag, har %s1 samlat in en belöning på %s2 poäng! %s1 har samlat in %s3 poäng från uppdrag denna säsong.\n"
Because %s1 is the name of the player, so it would be "har (namn) samlat...) Its supposed to be %s1 har samlat...

2024-03-27 18:09 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"rd_hoiaf_bounty_mission_bonus_claimed"		"Genom att klara av detta uppdrag, har %s1 samlat in en belöning på %s2 poäng! %s1 har samlat in %s3 poäng från uppdrag denna säsong.\n"
If you could get that reverted and change the other things mentioned

2024-03-27 18:36 UTC, icepic commented
For the record, whatever AI did the initial Swedish translation has left many weird and bad things in there. This was just a start, while trying to not change too much of string lengths and so forth, since I don't know how it might look when it's done if the strings change radically. I hope to be able to fix up lots of more things, but it would probably be better not to nitpick on lines that were left in there from the original. There is two words being used in the translation for "infested" and I think "infestering" or something like that is probably the better choice, whereas "Härjning" sounds really weird. That will be another PR later on.

2024-03-28 10:44 UTC, Duke-M-commits commented
Using machine help to translate is very useful, but also creates the new issue that the translation engine doesn't know about the context of your strings. Thus, some words get translated inconsistently. This is why I created a [lexicon](https://github.com/ReactiveDrop/reactivedrop_translations/wiki/Lexicon) of words in the Alien Swarm translator universe which lists everything susceptible to this issue.
One of you may want to copy & paste this list into a [GIST](https://gist.github.com/) and share it to the other one. So you both can work out on which wordings you finally agree.

2024-03-28 11:31 UTC, Crazymanbos commented
But I gotta double check it with the original game to see if it was like that or not.

2024-03-28 11:40 UTC, Crazymanbos commented
Yup. Its named Lågenhet in the original game. So why you gotta translate it to flamethrower (eldkastare). Such boring and generic names, thats why Lågenhet is better, its not boring and unique. So I dont like that change

2024-03-28 11:42 UTC, Crazymanbos reviewed
Changes for the flamethrower, Lågenhet in Swedish

2024-03-28 11:42 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_weaponl_flamer"		"M868 Eldkastarenhet"
Revert to Lågenhet

2024-03-28 11:42 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_take_ammo_flamer"		"Ta eldkastar-ammo"
Revert to Låg-ammo

2024-03-28 11:42 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_ammo_flamer"		"Eldkastar-ammo"
Revert to Låg-ammo

2024-03-28 11:42 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"asw_ammo_flamer_full"		"Fulla Eldkastarmagasin"
Revert to Lågmagasin

2024-03-28 11:42 UTC, Crazymanbos commented on resource/reactivedrop_swedish.txt
> +"ASW_FLAMER_KILLS_DESC"		"Döda 250 Svärminsekter med Eldkastarenheten."
Revert to Lågenheten

2024-03-28 11:45 UTC, Crazymanbos commented
For everyone else, "låg" is translated to flame in Swedish.

2024-03-28 13:28 UTC, icepic commented
While "låg" is flame, exactly zero people would translate flame thrower to "lågenhet", you can't even google for that because it just moves searches to "lägenhet". It makes it sound more related to "low" which also is "låg", so it reads more like  "low ammo", "low unit" and "low clips".  Just look at https://sv.wikipedia.org/wiki/Eldkastare#Etymologi which is talking about where the name comes from and alternative names used by the military.

Still, I respect if someone made a huge error once for the game and you want to stick to it. Just don't try to convince people that "lågenhet" is more correct or anything, it's just a matter of bringing the fault along to new releases.

2024-03-28 14:18 UTC, Crazymanbos commented
And in some lines the flamethrower is refered to flamer, so the Swedish version can have its own twist too.

2024-03-28 18:33 UTC, Duke-M-commits commented
> Well why does it have to be flamethrower exactly? Why couldnt it be unique like lågenhet that Valve even has, it doesnt have to be a error on their part of translating it, they maybe wanted it to be like that? Its still a game about killing aliens, what I know thats not so realistic in my opinion, so every name of weapons doesnt need to either be that. And some lines cant even be 100% be translated to Swedish, where you have to come up with own things to write, then why does this matter that we keep it as lågenhet?

I'm pretty sure Valve themselfs as the creators of their games never put any thoughts in unique namings afar from their english versions. I saw that in the german translation before I picked it up. First you should orientate yourself on what is used in the language of the native speakers in your country and after having that accomplished you can look into special nicknames for stuff. But these don't need to follow the same patterns as any existing ones in the english version. Such stuff is really "late game content" for when you are really really done with everything and have a good overview about everything there is in the whole content.

2024-03-29 01:34 UTC, BenLubar commented
In English, it's called the M868 Flamer Unit.

2024-04-02 22:06 UTC, BenLubar commented
superseded by #1477

2024-04-02 22:06 UTC, closed without merging