(multiple) small ui fixes for the options ui
ReactiveDrop/reactivedrop_translations pull request #1461
Opened 2024-03-26 19:44 UTC by Duke-M-commits

* fixed some cut off texts (english and german only)
* added some dots to sentences to improve reading consistency

2024-03-26 19:47 UTC, BenLubar requested changes

2024-03-26 19:47 UTC, BenLubar commented on resource/reactivedrop_english.txt
> +"rd_option_leaderboard_private_stats_hint"	"Hides most lifetime stats from your public commander profile. Experience, promotion and medals are still visible, excluding entries on individual leaderboa
I would interpret "excluding entries on individual leaderboards" to mean the opposite of the old text.

2024-03-26 19:47 UTC, BenLubar commented on resource/reactivedrop_english.txt
> +"rd_option_leaderboard_private_stats_hint"	"Hides most lifetime stats from your public commander profile. Experience, promotion and medals are still visible, excluding entries on individual leaderboa
maybe "as are" instead of "excluding"?

2024-03-26 20:01 UTC, Duke-M-commits commented
Should I outdent the few translations been made which are obviously too long also?

2024-03-26 20:18 UTC, BenLubar commented
> Should I outdent the few translations been made which are obviously too long also?

For now, just tag the translators of those specific lines and tell them to take a look.

2024-03-26 20:18 UTC, merged

2024-03-27 00:22 UTC, Duke-M-commits commented
@Blueberryy
![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/69652463/eff34a38-c3d3-440f-9fe8-1fefb87c3a03)

@MakinDay
![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/69652463/3f18bf12-6ad5-475a-8595-286f9b6c851c)