(multiple) better assault rifle description
ReactiveDrop/reactivedrop_translations pull request #1746
Opened 2024-11-09 00:16 UTC by Duke-M-commits

After reading about the description of the assault rifle being a bit confusing on [Discord](https://discord.com/channels/310381338538541056/310381338538541056/1304246470903337040) i went to fix it.

I've also machine-retranslated it, but since we do not have active translators for all languages (danish, hungarian, polish, portuguese, spanish, turkish) I went and indented the ones for which there is no one to look after.

Please review:
brazilian @Mart-User or @FurtadoPires
finnish @Crazymanbos
french @wawawawawawawa
italian @MakinDay or @Steffo99
japanese @Deerlord0 or @finishtw
korean @hangumi or @BRAIN-IS-BACK or @906bc906
latam @gaelcoral
russian @Blueberryy
schinese @ModdedMarionette or @ywgATustcbbs or @zhongqingsong
swedish @Crazymanbos
tchinese @ModdedMarionette or @Crazy3lf or @mewindng
ukrainian @MsSockol
vietnamese @DucDuyGaming

2024-11-09 00:24 UTC, Steffo99 reviewed
This sounds a bit better to me!

2024-11-09 00:24 UTC, Steffo99 commented on resource/reactivedrop_italian.txt
> +"asw_wdesc_rifle"		"Il 22A3-1 è l'arma di combattimento standard in dotazione ai soldati delle Forze Armate Interstellari (IAF). Grazie all'elevata cadenza di fuoco, ai proiettili esplosivi ad alta v
```suggestion
"asw_wdesc_rifle"		"Il 22A3-1 è l'arma di combattimento standard in dotazione ai soldati delle Forze Armate Interstellari (IAF). Grazie all'elevata cadenza di fuoco, ai proiettili esplosivi ad alta velocità e al lanciagranate sottocanna, quest'arma offre una notevole versatilità sul campo, essendo in grado di abbattere bersagli piccoli e grandi. La dimensione standard del caricatore è di 98 colpi."
```

2024-11-09 00:59 UTC, 906bc906 commented on resource/reactivedrop_koreana.txt
> +"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 빠른 발사 속도, 고속 폭발성 팁 탄과 언더슬링 유탄 발사기를 모두 갖추고 있어 작은 목표물과 큰 목표물을 모두 쓰러뜨릴 수 있어 현장에서 활용도가 매우 높습니다. 기본 탄창 크기는 98발입니다."
needs to be changed, but I'd like to hear from other Korean translators about how to retranslate.

Please wait for suggestion from @hangumi 

```suggestion
"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 높은 연사력과 언더배럴 유탄발사기의 고속 고폭탄을 통해 크고 작은 목표물을 모두 쓰러뜨릴 수 있어 전장에서의 범용성이 매우 우수합니다. 기본 탄창 크기는 98발입니다."
```

2024-11-09 04:54 UTC, finishtw commented on resource/reactivedrop_tchinese.txt
> +"asw_wdesc_rifle"		"22A3-1突擊步槍是星際武裝部隊的標準作戰武器。這款武器提供高射速和高速爆炸彈，適用於下掛式榴彈發射器，在實戰中具有顯著的多功能性，能夠擊倒小型和大型目標。其標準彈匣容量是98發。"
This should be better
```suggestion
"asw_wdesc_rifle"		"22A3-1突擊步槍是星際武裝部隊的標準作戰武器。其具備高射速機能和下掛式榴彈發射器所使用的高爆彈藥，在戰場中適用於不同用途，能夠擊倒小型和大型目標。其標準彈匣容量是98發。"
```

2024-11-09 14:48 UTC, Crazymanbos commented on resource/reactivedrop_finnish.txt
> +"asw_wdesc_rifle"		"22A3-1 on Tähtienvälisten Asevoimien jääkärin palveluskivääri. Tämä ase tarjoaa sekä suuren tulinopeuden, suuren nopeuden räjähdekärjellä varustetut ammukset että alhaalla olevan
Looks good to me.

2024-11-09 17:01 UTC, hangumi commented on resource/reactivedrop_koreana.txt
> +"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 빠른 발사 속도, 고속 폭발성 팁 탄과 언더슬링 유탄 발사기를 모두 갖추고 있어 작은 목표물과 큰 목표물을 모두 쓰러뜨릴 수 있어 현장에서 활용도가 매우 높습니다. 기본 탄창 크기는 98발입니다."
> needs to be changed, but I'd like to hear from other Korean translators about how to retranslate.
> 
> Please wait for suggestion from @hangumi 
> 
> ```suggestion
> "asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 높은 연사력과 언더배럴 유탄발사기의 고속 고폭탄을 통해 크고 작은 목표물을 모두 쓰러뜨릴 수 있어 전장에서의 범용성이 매우 우수합니다. 기본 탄창 크기는 98발입니다."
> ```

언더배럴을 하단부착으로만 바꾸시면 괜찮을 것 같습니다.

2024-11-09 17:04 UTC, Crazy3lf approved these changes

2024-11-09 18:08 UTC, 906bc906 commented on resource/reactivedrop_koreana.txt
> +"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 빠른 발사 속도, 고속 폭발성 팁 탄과 언더슬링 유탄 발사기를 모두 갖추고 있어 작은 목표물과 큰 목표물을 모두 쓰러뜨릴 수 있어 현장에서 활용도가 매우 높습니다. 기본 탄창 크기는 98발입니다."
Looks good to me. @Duke-M-commits

2024-11-09 18:26 UTC, 906bc906 commented on resource/reactivedrop_koreana.txt
> +"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 빠른 발사 속도, 고속 폭발성 팁 탄과 언더슬링 유탄 발사기를 모두 갖추고 있어 작은 목표물과 큰 목표물을 모두 쓰러뜨릴 수 있어 현장에서 활용도가 매우 높습니다. 기본 탄창 크기는 98발입니다."
> 언더배럴을 하단부착으로만 바꾸시면 괜찮을 것 같습니다.

He suggested changing `언더배럴(underbarrel in Korean)` to `하단부착(underslung in Korean)`, and this text reflects that change. @Duke-M-commits 

```suggestion
"asw_wdesc_rifle"		"22A3-1 돌격 소총은 성간 무장 부대의 해병들에게 기본으로 지급되는 무기입니다. 이 무기는 높은 연사력과 하단부착 유탄발사기의 고속 고폭탄을 통해 크고 작은 목표물을 모두 쓰러뜨릴 수 있어 전장에서의 범용성이 매우 우수합니다. 기본 탄창 크기는 98발입니다."
```

2024-11-10 06:04 UTC, Deerlord0 requested changes
sent a fix for new AR description.

2024-11-10 06:04 UTC, Deerlord0 commented on resource/reactivedrop_japanese.txt
> +"asw_wdesc_rifle"		"22A3-1アサルトライフルはIAFの海兵隊に支給される標準装備だ。 この武器は、高火力、高速の爆発性チップ弾と、下方に吊り下げられたグレネード・ランチャーの両方を備えており、小型のターゲットから大型のターゲットまで倒すことができる。 標準の弾倉サイズは98発入り。"
"asw_wdesc_rifle"		"22A3-1アサルトライフルはIAFの海兵隊に支給される標準装備だ。 高い連射性能を持ち、銃身下に装着されたグレネードランチャーからは炸裂弾を高速で射出できる。 この武器は戦場での汎用性がとても高く、敵が小型でも大型でも相手にできる。 標準の弾倉サイズは98発入り。"

2024-11-10 15:00 UTC, Steffo99 approved these changes

2024-11-12 11:51 UTC, DucDuyGaming requested changes
I think I forgot to submit the review, here you go

2024-11-19 13:03 UTC, Duke-M-commits commented
I've indented lines which nobody found time to look at. 
@BenLubar I think we're good to go

2024-11-20 00:34 UTC, merged