Minor improvements and cosmetic corrections for Bastille.
ReactiveDrop/reactivedrop_translations pull request #893
Opened 2023-05-14 18:12 UTC by NGCHunter2

2023-05-15 12:40 UTC, DukeDukeEm requested changes
Bis auf Kleinigkeiten sind das alles super Verbesserungen.

2023-05-15 12:40 UTC, DukeDukeEm commented on resource/closecaption_german.txt
> +"bastille.Use3"		"<clr:205,127,50>Bastille: Immediatement."
Ich mag das der Franzose auch mal was in seiner Sprache beantworted. Gut mitgedacht. Aber wenn wir schon so genau sind gehen wir gleich in die Vollen und nehmen die Schreibung mit Akut (über dem e).
Immédiatement.

2023-05-15 12:40 UTC, DukeDukeEm commented on resource/closecaption_german.txt
> +"bastille.HoldingEast3"		"<clr:205,127,50>Bastille: Osten ist in Position."
Ostseite in Position.
Usw. bei den nächsten Vorkommnissen.

Ich muss zugeben ich habe da selbst noch nicht so sehr darüber nachgedacht. Aber jetzt wo du es geändert hast machen wir es am besten noch genauer.

2023-05-15 15:21 UTC, NGCHunter2 commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
Wohl wahr; ich war anfangs versucht, näher am englischen Original ("I've got" im Sinne von "ich melde mich für…") zu bleiben und "übernehme die Ostseite" --> "übernehme den Osten" zu schreiben, was (vorsichtig ausgedrückt…) noch etwas unglücklicher klang als mein letztendlicher Commit. "Halte die Ostseite" passt da in der Tat besser; soll ich dies auf die anderen drei Seiten ausweiten, der Vereinheitlichung halber? "Halte die Nord-/West-/Südseite"?

2023-05-15 19:57 UTC, DukeDukeEm commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
Auf alle Seiten ausweiten. Ja. 
Überall würde ich sagen wenn ich gerade so drüber schaue. "Ich habe die Nordseite." klingt mMn besser als "Ich habe den Norden".

2023-05-15 20:05 UTC, DukeDukeEm commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
@BenLubar do different versions of an marine screaming something get selected in a row or at random?

2023-05-15 20:13 UTC, NGCHunter2 commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
> Da einer der Befehle (von gleichem Key und unterschiedlicher Nummer) zufällig ausgewählt wird und sie nicht unbedingt aufeinander folgen sind Doppelungen, glaube ich, kein Problem.

Sollte passen, denke ich; habe bei einer Variante das "ich" gestrichen, somit sind es wieder vier unterschiedliche Optionen, ohne dass der zu vermittelnde Inhalt verloren geht. Gerne Rückmeldung, ob das deiner Meinung nach so akzeptabel ist.

2023-05-16 01:23 UTC, BenLubar commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
> @BenLubar do different versions of an marine screaming something get selected in a row or at random?

It is random each time (it does not remember which version of a line was played previously).

2023-05-16 06:27 UTC, DukeDukeEm approved these changes

2023-05-16 06:29 UTC, DukeDukeEm commented on resource/closecaption_german.txt
> +"bastille.HoldingEast2"		"<clr:205,127,50>Bastille: Halte den Osten."
Ok, perfect, I would say then we are ready here :)

2023-05-16 14:26 UTC, DukeDukeEm approved these changes

2023-05-17 22:14 UTC, merged